cov

diff --git a/.github/workflows/back-build-test.yml b/.github/workflows/back-build-test.yml
--- a/.github/workflows/back-build-test.yml
+++ b/.github/workflows/back-build-test.yml
@@ -43,19 +43,19 @@ jobs:
               run: |
                 ls ${{ github.workspace }}/back/target/site/jacoco/*
 
-            - name: JUnit Test Report
-              uses: phoenix-actions/test-reporting@v8
-              id: junit-test-report
-              if: success() || failure()
-              with:
-                name: JUNIT Tests
-                path: 'target/site/jacoco/*.*'
-                reporter: jest-junit
-                working-directory: back
+            # - name: JUnit Test Report
+            #   uses: phoenix-actions/test-reporting@v8
+            #   id: junit-test-report
+            #   if: success() || failure()
+            #   with:
+            #     name: JUNIT Tests
+            #     path: 'target/site/jacoco/*.*'
+            #     reporter: jest-junit
+            #     working-directory: back
 
-            - name: Read output variables
-              run: |
-                echo "url is ${{ steps.junit-test-report.outputs.runHtmlUrl }}"
+            # - name: Read output variables
+            #   run: |
+            #     echo "url is ${{ steps.junit-test-report.outputs.runHtmlUrl }}"
 
             
             
diff --git a/.github/workflows/front-build-test.yml b/.github/workflows/front-build-test.yml
--- a/.github/workflows/front-build-test.yml
+++ b/.github/workflows/front-build-test.yml
@@ -45,18 +45,18 @@ jobs:
                 flags: frontend
                 working-directory: front
 
-            - name: Jest Test Report
-              uses: phoenix-actions/test-reporting@v8
-              id: jest-test-report
-              if: success() || failure()
-              with:
-                name: JEST Tests
-                path: 'coverage/bobapp/*.*' 
-                # path: 'coverage/bobapp/*.* , coverage/bobapp/app/*.* , coverage/bobapp/app/**/*.*' 
-                reporter: jest-junit 
-                working-directory: front
+            # - name: Jest Test Report
+            #   uses: phoenix-actions/test-reporting@v8
+            #   id: jest-test-report
+            #   if: success() || failure()
+            #   with:
+            #     name: JEST Tests
+            #     path: 'coverage/bobapp/*.*' 
+            #     # path: 'coverage/bobapp/*.* , coverage/bobapp/app/*.* , coverage/bobapp/app/**/*.*' 
+            #     reporter: jest-junit 
+            #     working-directory: front
 
-            - name: Read output variables
-              run: |
-                echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"
+            # - name: Read output variables
+            #   run: |
+            #     echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"
 
