test

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -32,6 +32,20 @@ jobs:
               run: mvn clean test
               working-directory: back
 
+            # - name: JUnit Test Report
+            #   uses: phoenix-actions/test-reporting@v8
+            #   id: junit-test-report
+            #   if: success() || failure()
+            #   with:
+            #     name: JUNIT Tests
+            #     path: '**/target/site/jacoco/index.html'
+            #     reporter: jest-junit
+            #     working-directory: back
+
+            # - name: Read output variables
+            #   run: |
+            #     echo "url is ${{ steps.junit-test-report.outputs.runHtmlUrl }}"
+
             - name: Front Install Dependencies
               run: npm install
               working-directory: front
@@ -41,6 +55,21 @@ jobs:
               working-directory: front
 
             - name: Front Test
-              run: npm run test -- --watch=true --browsers=ChromeHeadless
+              # run: npm run test -- --watch=false --browsers=ChromeHeadless
+              run: npx jest --coverage
               working-directory: front
+
+            - name: Jest Test Report
+              uses: phoenix-actions/test-reporting@v8
+              id: jest-test-report
+              if: success() || failure()
+              with:
+                name: JEST Tests
+                path: '**/coverage/jest/lcov-report/index.html'
+                reporter: jest-junit 
+                working-directory: front
+
+            - name: Read output variables
+              run: |
+                echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"
 
