back report

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -29,22 +29,22 @@ jobs:
               working-directory: back
 
             - name: Back Test
-              run: mvn clean test
+              run: mvn clean test -DEBUG=mocha*
               working-directory: back
 
-            # - name: JUnit Test Report
-            #   uses: phoenix-actions/test-reporting@v8
-            #   id: junit-test-report
-            #   if: success() || failure()
-            #   with:
-            #     name: JUNIT Tests
-            #     path: '**/target/site/jacoco/index.html'
-            #     reporter: jest-junit
-            #     working-directory: back
+            - name: JUnit Test Report
+              uses: phoenix-actions/test-reporting@v8
+              id: junit-test-report
+              if: success() || failure()
+              with:
+                name: JUNIT Tests
+                path: '**/target/site/jacoco/index.html'
+                reporter: jest-junit
+                working-directory: back
 
-            # - name: Read output variables
-            #   run: |
-            #     echo "url is ${{ steps.junit-test-report.outputs.runHtmlUrl }}"
+            - name: Read output variables
+              run: |
+                echo "url is ${{ steps.junit-test-report.outputs.runHtmlUrl }}"
 
             - name: Front Install Dependencies
               run: npm install
@@ -58,17 +58,17 @@ jobs:
               run: npm run test -- --code-coverage=true --watch=false --browsers=ChromeHeadless
               working-directory: front
 
-            - name: Jest Test Report
-              uses: phoenix-actions/test-reporting@v8
-              id: jest-test-report
-              if: success() || failure()
-              with:
-                name: JEST Tests
-                path: '**/coverage/bobapp/index.html'
-                reporter: jest-junit 
-                working-directory: front
+            # - name: Jest Test Report
+            #   uses: phoenix-actions/test-reporting@v8
+            #   id: jest-test-report
+            #   if: success() || failure()
+            #   with:
+            #     name: JEST Tests
+            #     path: '**/coverage/bobapp/index.html'
+            #     reporter: jest-junit 
+            #     working-directory: front
 
-            - name: Read output variables
-              run: |
-                echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"
+            # - name: Read output variables
+            #   run: |
+            #     echo "url is ${{ steps.jest-test-report.outputs.runHtmlUrl }}"
 
